apiVersion: "tinkerbell.org/v1alpha1"
kind: Template
metadata:
  name: debian
spec:
  data: |
    version: "0.1"
    name: debian
    global_timeout: 1800
    tasks:
      - name: "os-installation"
        worker: "{{.device_1}}"
        volumes:
          - /dev:/dev
          - /dev/console:/dev/console
          - /lib/firmware:/lib/firmware:ro
        actions:
          - name: "stream-debian-image"
            image: quay.io/tinkerbell-actions/image2disk:v1.0.0
            timeout: 600
            environment:
              DEST_DISK: /dev/nvme0n1
              # Hegel IP
              IMG_URL: "http://10.1.1.11:8080/debian-10-openstack-amd64.raw.gz"
              COMPRESSED: true
          - name: "add-tink-cloud-init-config"
            image: writefile:v1.0.0
            timeout: 90
            environment:
              DEST_DISK: /dev/nvme0n1p1
              FS_TYPE: ext4
              DEST_PATH: /etc/cloud/cloud.cfg.d/10_tinkerbell.cfg
              UID: 0
              GID: 0
              MODE: 0600
              DIRMODE: 0700
              CONTENTS: |
                datasource:
                  Ec2:
                    # Hegel IP
                    metadata_urls: ["http://10.1.1.11:50061"]
                    strict_id: false
                system_info:
                  default_user:
                    name: tink
                    groups: [wheel, adm, sudo]
                    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
                    shell: /bin/bash
                users:
                - name: tink
                  sudo: ["ALL=(ALL) NOPASSWD:ALL"]
                  ssh_authorized_keys:
                    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDf//aq5bmEgzlzPF102taupa+hsy7n7ZEQYth6NCbdVQ3FhtV/aYqStjtS8UIiUHf+7hTK8llHR8/yC/EEdgYORdU6p8W3aSedNsqU/IMPMX9HkLK2Zz0FHg201lDW1mvCjgUX7VC0bsvz0NY5CDceea9G42c1HfBPEjf8KugegcWFH0FOnJ9P3/ObcaF9IcA5KasNoQyYhgV7sIxPKNHVUYhMLFWR4OwBdoiU8xaVV67LhFERemoo935bwONDboXjmJWrQmGC1Vhy+1YH9feXnSk4gS1wCSsRmSQ/YZUDLbLXT/JfD1SgKwGkjqsFyJVTr6af7TDjn1InWLdAxb5IKeUCUOB1U1BtqcBWdPNddAItYpHZ8tC/EuixmRyo0EOpSWJWu8hIXa13AU8v2mMEM0hH750ANXE65/bgvysIoVaaa285wESipj6+5BfZ4v79TEdIoIZ1yw5b75yb17HAYpwf2GQvFOf58JOGKtnewO61f1KLI3QMPRegW6aFYTc="
                warnings:
                  dsid_missing_source: off
          - name: "add-tink-cloud-init-ds-config"
            image: writefile:v1.0.0
            timeout: 90
            environment:
              DEST_DISK: /dev/nvme0n1p1
              FS_TYPE: ext4
              DEST_PATH: /etc/cloud/ds-identify.cfg
              UID: 0
              GID: 0
              MODE: 0600
              DIRMODE: 0700
              CONTENTS: |
                datasource: Ec2
          - name: "kexec-debian"
            image: quay.io/tinkerbell-actions/kexec:v1.0.1
            timeout: 90
            pid: host
            environment:
              BLOCK_DEVICE: /dev/nvme0n1p1
              FS_TYPE: ext4
